[programs.localnet]
frons = "95eTYR6AW9u7RExdHmZwr7LuLbgZM83aqAUkEFV5me89"

[programs.devnet]
frons = "95eTYR6AW9u7RExdHmZwr7LuLbgZM83aqAUkEFV5me89"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
devnet-deploy = "anchor deploy --provider.cluster devnet"
