[programs.localnet]
frons = "FroNs1111111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
devnet-deploy = "anchor deploy --provider.cluster devnet"
